apiVersion: apps/v1
kind: Deployment
metadata:
  name: poclistener
  labels:
    app: poclistener
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poclistener
  template:
    metadata:
      labels:
        app: poclistener
    spec:
      containers:
       - name: poclistener
         image: dhanapodigiri/poclistener:1.0.0-73
         ports:
         - containerPort: 8081
         imagePullPolicy: Always
         volumeMounts:
         - name: volumekafkalistener
           mountPath: /tmp
      volumes:
      - name: volumekafkalistener
        configMap:
         name: kafkalistener-cm
      imagePullSecrets:
       - name: gcr-json-key

